// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'purple-dark', 'purple-light', 'blue-dark', 'blue-light', 'orange-dark', 'orange-light', 'yellow-dark', 'yellow-light']
    }
}

export {}
